In [ ]:
#INSTALL LIBRARIES

!pip install datasets sentence-transformers faiss-cpu rank_bm25 wikipedia pandas numpy tqdm scikit-learn openai -q

In [ ]:
# ============================================================
# 1. IMPORTS
# ============================================================

import os
import re
import time
import faiss
import numpy as np
import pandas as pd
import wikipedia
from tqdm import tqdm
from datasets import load_dataset
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, CrossEncoder
from sklearn.metrics import precision_score

In [ ]:
# ============================================================
# 2. LOAD POPQA DATASET
# ============================================================

dataset = load_dataset("akariasai/PopQA")
data = dataset["test"].to_pandas()

print("Dataset shape:", data.shape)
print("Columns:")
print(data.columns.tolist())

data.head()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

test.tsv: 0.00B [00:00, ?B/s]

Generating test split:   0%|          | 0/14267 [00:00<?, ? examples/s]

Dataset shape: (14267, 17)
Columns:
['id', 'subj', 'prop', 'obj', 'subj_id', 'prop_id', 'obj_id', 's_aliases', 'o_aliases', 's_uri', 'o_uri', 's_wiki_title', 'o_wiki_title', 's_pop', 'o_pop', 'question', 'possible_answers']

,id,subj,prop,obj,subj_id,prop_id,obj_id,s_aliases,o_aliases,s_uri,o_uri,s_wiki_title,o_wiki_title,s_pop,o_pop,question,possible_answers
0,4222362,George Rankin,occupation,politician,1850297,22,2834605,"[""George James Rankin""]","[""political leader"",""political figure"",""polit....",http://www.wikidata.org/entity/Q5543720,http://www.wikidata.org/entity/Q82955,George Rankin,Politician,142,25692,What is George Rankin's occupation?,"[""politician"", ""political leader"", ""political ..."
1,4725190,John Mayne,occupation,journalist,2079053,22,663400,[],"[""journo"",""journalists""]",http://www.wikidata.org/entity/Q6247345,http://www.wikidata.org/entity/Q1930187,John Mayne,Journalist,236,24952,What is John Mayne's occupation?,"[""journalist"", ""journo"", ""journalists""]"
2,4382392,Henry Feilden,occupation,politician,1925450,22,2834605,"[""Henry Master Feilden""]","[""political leader"",""political figure"",""polit....",http://www.wikidata.org/entity/Q5725578,http://www.wikidata.org/entity/Q82955,Henry Feilden (Conservative politician),Politician,58,25692,What is Henry Feilden's occupation?,"[""politician"", ""political leader"", ""political ..."
3,4822110,Kathy Saltzman,occupation,politician,2122743,22,2834605,[],"[""political leader"",""political figure"",""polit....",http://www.wikidata.org/entity/Q6377295,http://www.wikidata.org/entity/Q82955,Kathy Saltzman,Politician,127,25692,What is Kathy Saltzman's occupation?,"[""politician"", ""political leader"", ""political ..."
4,4011112,Eleanor Davis,occupation,cartoonist,1752619,22,68412,"[""Eleanor McCutcheon Davis""]","[""graphic artist"",""animator"",""illustrator""]",http://www.wikidata.org/entity/Q5354261,http://www.wikidata.org/entity/Q1114448,Eleanor Davis,Cartoonist,317,9649,What is Eleanor Davis's occupation?,"[""cartoonist"", ""graphic artist"", ""animator"", ""..."

In [ ]:
# ============================================================
# 3. SELECT SMALL EVALUATION SUBSET
# ============================================================

EVAL_SIZE = 50

df = data.sample(n=EVAL_SIZE, random_state=42).reset_index(drop=True)

print("Selected evaluation subset:", df.shape)
df[["question", "possible_answers"]].head()

Selected evaluation subset: (50, 17)

,question,possible_answers
0,Who was the screenwriter for On the Town?,"[""Betty Comden"", ""Basya Cohen"", ""Adolph Green""]"
1,What is the religion of Juan Soldevilla y Romero?,"[""Catholic Church"", ""Roman Catholic Church"", ""..."
2,What genre is Haddaway?,"[""Eurodance"", ""Euro-dance"", ""Euro dance""]"
3,Who was the composer of Chances Are?,"[""Maurice Jarre"", ""Maurice-Alexis Jarre""]"
4,Who was the producer of The Pioneers?,"[""Franklyn Barrett"", ""Walter Franklyn Barrett""]"

In [ ]:
# ============================================================
# 4. HELPER FUNCTIONS
# ============================================================

def clean_text(text):
    text = re.sub(r"\s+", " ", str(text))
    return text.strip()

def normalize_answer(ans):
    ans = str(ans).lower()
    ans = re.sub(r"[^a-z0-9\s]", "", ans)
    return ans.strip()

def get_gold_answers(row):
    """
    PopQA possible_answers can be stored as list-like text.
    This function makes it easier to evaluate.
    """
    answers = row["possible_answers"]

    if isinstance(answers, list):
        return [normalize_answer(a) for a in answers]

    answers = str(answers)
    answers = answers.replace("[", "").replace("]", "").replace("'", "").replace('"', "")
    answers = answers.split(",")
    return [normalize_answer(a) for a in answers if len(a.strip()) > 0]

def contains_gold_answer(text, gold_answers):
    text_norm = normalize_answer(text)
    return any(ans in text_norm for ans in gold_answers if ans)

In [ ]:
# ============================================================
# 5. BUILD WIKIPEDIA CORPUS
# ============================================================

def fetch_wikipedia_page(title):
    try:
        return wikipedia.page(title, auto_suggest=False).content
    except:
        try:
            return wikipedia.summary(title, sentences=10, auto_suggest=True)
        except:
            return ""

def chunk_text(text, chunk_size=120, overlap=30):
    words = text.split()
    chunks = []

    for i in range(0, len(words), chunk_size - overlap):
        chunk = words[i:i + chunk_size]
        if len(chunk) > 30:
            chunks.append(" ".join(chunk))

    return chunks

corpus = []
seen_titles = set()

for idx, row in tqdm(df.iterrows(), total=len(df)):
    titles = []

    if "s_wiki_title" in df.columns and pd.notna(row["s_wiki_title"]):
        titles.append(row["s_wiki_title"])

    if "o_wiki_title" in df.columns and pd.notna(row["o_wiki_title"]):
        titles.append(row["o_wiki_title"])

    for title in titles:
        title = str(title)
        if title in seen_titles:
            continue

        seen_titles.add(title)
        text = fetch_wikipedia_page(title)
        text = clean_text(text)

        if len(text) == 0:
            continue

        chunks = chunk_text(text)

        for chunk_id, chunk in enumerate(chunks):
            corpus.append({
                "passage_id": f"{title.replace(' ', '_')}_{chunk_id}",
                "title": title,
                "text": chunk
            })

corpus_df = pd.DataFrame(corpus)

print("Number of passages:", len(corpus_df))
corpus_df.head()

 16%|█▌        | 8/50 [00:10<00:55,  1.32s/it]/usr/local/lib/python3.12/dist-packages/wikipedia/wikipedia.py:389: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 389 of the file /usr/local/lib/python3.12/dist-packages/wikipedia/wikipedia.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  lis = BeautifulSoup(html).find_all('li')
100%|██████████| 50/50 [01:05<00:00,  1.31s/it]

Number of passages: 3228

,passage_id,title,text
0,On_the_Town_(film)_0,On the Town (film),On the Town is a 1949 American Technicolor mus...
1,On_the_Town_(film)_1,On the Town (film),"Edens, who felt that the majority of Bernstein..."
2,On_the_Town_(film)_2,On the Town (film),"in New York City, including Columbus Circle, t..."
3,On_the_Town_(film)_3,On the Town (film),Film Registry by the Library of Congress as be...
4,On_the_Town_(film)_4,On the Town (film),"train, Gabey vows to find her again. The sailo..."

In [ ]:
# ============================================================
# 6. CREATE DENSE VECTOR INDEX
# ============================================================

embedding_model_name = "sentence-transformers/all-MiniLM-L6-v2"
embedder = SentenceTransformer(embedding_model_name)

passages = corpus_df["text"].tolist()

passage_embeddings = embedder.encode(
    passages,
    convert_to_numpy=True,
    show_progress_bar=True,
    normalize_embeddings=True
)

dimension = passage_embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)
index.add(passage_embeddings)

print("Embedding model:", embedding_model_name)
print("Embedding dimension:", dimension)
print("Total indexed passages:", index.ntotal)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/101 [00:00<?, ?it/s]

Embedding model: sentence-transformers/all-MiniLM-L6-v2
Embedding dimension: 384
Total indexed passages: 3228

In [ ]:
# ============================================================
# 7. BASELINE DENSE RETRIEVER
# ============================================================

def dense_retrieve(query, top_k=5):
    query_emb = embedder.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    scores, ids = index.search(query_emb, top_k)

    results = []
    for score, idx in zip(scores[0], ids[0]):
        row = corpus_df.iloc[idx]
        results.append({
            "passage_id": row["passage_id"],
            "title": row["title"],
            "text": row["text"],
            "score": float(score)
        })

    return results

# Test retrieval on 3 queries
for q in df["question"].head(3):
    print("\nQUESTION:", q)
    results = dense_retrieve(q, top_k=3)
    for r in results:
        print(r["passage_id"], "|", r["text"][:200])

QUESTION: Who was the screenwriter for On the Town?
Montgomery_Tully_1 | 1967. He also worked in television, directing episodes of shows including Edgar Wallace Mysteries, Kraft Mystery Theatre, Man from Interpol and Fabian of the Yard. == Partial filmography == == Referen
The_City_(1916_film)_0 | The City is a lost 1916 silent film based on Clyde Fitch's 1909 play, The City. It was distributed by the World Film Company. == Cast == Thurlow Bergen - George Rand, Jr. Riley Hatch - George Rand, Sr
Last_Night_(2010_film)_9 | that their struggle was believable". After a negative response from a Warner Bros. studio executive on the script's formatting, she realized Final Draft was the preferred software for screenwriters. I

QUESTION: What is the religion of Juan Soldevilla y Romero?
Juan_Soldevilla_y_Romero_0 | Juan Soldevila y Romero (29 October 1843 – 4 June 1923) was a Spanish Cardinal of the Roman Catholic Church who served as Archbishop of Zaragoza from 1901 until his death, and was elevated to the rank
Juan_Soldevilla_y_Romero_1 | canon law at the seminary in Tuy. Soldevila served as a curate in three parishes in the Archdiocese of Valladolid, and became secretary to the Archbishop, Cesáreo Rodrigo y Rodríguez (1875), a cathedr
Juan_Soldevilla_y_Romero_4 | of anarchist leader Salvador Seguí. He is buried at the Basilica of Our Lady of the Pillar. == References == == External links == Cardinals of the Holy Roman Church Catholic-Hierarchy [self-published]

QUESTION: What genre is Haddaway?
The_Album_(Haddaway_album)_0 | The Album (also known as Haddaway in North America and L'Album in France) is the debut album by Trinidadian-German Eurodance recording artist Haddaway, released in September 1993 by Coconut Records. I
The_Album_(Haddaway_album)_3 | on The Album, additional backing vocals on The Album 2nd Edition by Elkie Schlimbach, Rena T. Otta Alex Trime – keyboards == Charts == == Certifications and sales == == References == == External links
Washington,_D.C._78 | was one of the most crucial independent labels in the genesis of 1980s punk and eventually indie rock in the 1990s. Modern alternative and indie music venues like The Black Cat and the 9:30 Club bring

In [ ]:
# ============================================================
# 8. RETRIEVAL METRICS
# ============================================================

def evaluate_retriever(retriever_func, dataframe, top_k_values=[1, 3, 5]):
    results = {
        "Recall@1": 0,
        "Recall@3": 0,
        "Recall@5": 0,
        "Precision@1": 0,
        "Precision@3": 0,
        "Precision@5": 0,
        "MRR": 0
    }

    for _, row in tqdm(dataframe.iterrows(), total=len(dataframe)):
        question = row["question"]
        gold_answers = get_gold_answers(row)

        retrieved = retriever_func(question, top_k=max(top_k_values))
        hits = [contains_gold_answer(r["text"], gold_answers) for r in retrieved]

        for k in top_k_values:
            top_hits = hits[:k]
            results[f"Recall@{k}"] += int(any(top_hits))
            results[f"Precision@{k}"] += sum(top_hits) / k

        reciprocal_rank = 0
        for rank, hit in enumerate(hits, start=1):
            if hit:
                reciprocal_rank = 1 / rank
                break

        results["MRR"] += reciprocal_rank

    n = len(dataframe)
    for key in results:
        results[key] = results[key] / n

    return results

baseline_metrics = evaluate_retriever(dense_retrieve, df)

baseline_table = pd.DataFrame([baseline_metrics], index=["Dense Baseline"])
baseline_table

100%|██████████| 50/50 [00:01<00:00, 31.72it/s]

,Recall@1,Recall@3,Recall@5,Precision@1,Precision@3,Precision@5,MRR
Dense Baseline,0.62,0.74,0.82,0.62,0.346667,0.32,0.699

In [ ]:
# ============================================================
# 9. QUERY EXPANSION
# ============================================================

def expand_query(query):
    """
    Simple keyword/entity-style expansion.
    This avoids needing an API key.
    """
    expansion_terms = [
        "biography",
        "history",
        "known for",
        "was",
        "is"
    ]
    return query + " " + " ".join(expansion_terms)

def expanded_dense_retrieve(query, top_k=5):
    expanded = expand_query(query)
    return dense_retrieve(expanded, top_k=top_k)

# Show examples
for q in df["question"].head(5):
    print("Original:", q)
    print("Expanded:", expand_query(q))
    print()

Original: Who was the screenwriter for On the Town?
Expanded: Who was the screenwriter for On the Town? biography history known for was is

Original: What is the religion of Juan Soldevilla y Romero?
Expanded: What is the religion of Juan Soldevilla y Romero? biography history known for was is

Original: What genre is Haddaway?
Expanded: What genre is Haddaway? biography history known for was is

Original: Who was the composer of Chances Are?
Expanded: Who was the composer of Chances Are? biography history known for was is

Original: Who was the producer of The Pioneers?
Expanded: Who was the producer of The Pioneers? biography history known for was is

In [ ]:
expanded_metrics = evaluate_retriever(expanded_dense_retrieve, df)

pd.DataFrame(
    [baseline_metrics, expanded_metrics],
    index=["Dense Baseline", "Dense + Query Expansion"]
)

100%|██████████| 50/50 [00:01<00:00, 37.49it/s]

,Recall@1,Recall@3,Recall@5,Precision@1,Precision@3,Precision@5,MRR
Dense Baseline,0.62,0.74,0.82,0.62,0.346667,0.320,0.699000
Dense + Query Expansion,0.52,0.70,0.76,0.52,0.340000,0.304,0.619667

In [ ]:
# ============================================================
# 10. BM25 LEXICAL RETRIEVER
# ============================================================

def tokenize(text):
    return re.findall(r"\b\w+\b", text.lower())

tokenized_corpus = [tokenize(p) for p in passages]
bm25 = BM25Okapi(tokenized_corpus)

def bm25_retrieve(query, top_k=5):
    tokenized_query = tokenize(query)
    scores = bm25.get_scores(tokenized_query)
    top_indices = np.argsort(scores)[::-1][:top_k]

    results = []
    for idx in top_indices:
        row = corpus_df.iloc[idx]
        results.append({
            "passage_id": row["passage_id"],
            "title": row["title"],
            "text": row["text"],
            "score": float(scores[idx])
        })

    return results

In [ ]:
# ============================================================
# 11. HYBRID SEARCH USING RECIPROCAL RANK FUSION
# ============================================================

def reciprocal_rank_fusion(result_lists, k=60, top_k=5):
    scores = {}
    passage_map = {}

    for results in result_lists:
        for rank, item in enumerate(results, start=1):
            pid = item["passage_id"]
            scores[pid] = scores.get(pid, 0) + 1 / (k + rank)
            passage_map[pid] = item

    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)

    final_results = []
    for pid, score in ranked[:top_k]:
        item = passage_map[pid]
        item = item.copy()
        item["score"] = float(score)
        final_results.append(item)

    return final_results

def hybrid_retrieve(query, top_k=5):
    dense_results = dense_retrieve(query, top_k=20)
    bm25_results = bm25_retrieve(query, top_k=20)
    return reciprocal_rank_fusion([dense_results, bm25_results], top_k=top_k)

hybrid_metrics = evaluate_retriever(hybrid_retrieve, df)

pd.DataFrame(
    [baseline_metrics, expanded_metrics, hybrid_metrics],
    index=["Dense Baseline", "Dense + Query Expansion", "Hybrid BM25 + Dense"]
)

100%|██████████| 50/50 [00:02<00:00, 24.90it/s]

,Recall@1,Recall@3,Recall@5,Precision@1,Precision@3,Precision@5,MRR
Dense Baseline,0.62,0.74,0.82,0.62,0.346667,0.320,0.699000
Dense + Query Expansion,0.52,0.70,0.76,0.52,0.340000,0.304,0.619667
Hybrid BM25 + Dense,0.56,0.76,0.82,0.56,0.406667,0.340,0.666333

In [ ]:
# ============================================================
# 12. RERANKING WITH CROSS-ENCODER
# ============================================================

reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

def hybrid_rerank_retrieve(query, top_k=5):
    candidates = hybrid_retrieve(query, top_k=20)

    pairs = [(query, c["text"]) for c in candidates]
    scores = reranker.predict(pairs)

    for c, score in zip(candidates, scores):
        c["rerank_score"] = float(score)

    ranked = sorted(candidates, key=lambda x: x["rerank_score"], reverse=True)
    return ranked[:top_k]

reranked_metrics = evaluate_retriever(hybrid_rerank_retrieve, df)

comparison_table = pd.DataFrame(
    [baseline_metrics, expanded_metrics, hybrid_metrics, reranked_metrics],
    index=[
        "Dense Baseline",
        "Dense + Query Expansion",
        "Hybrid BM25 + Dense",
        "Hybrid + Reranking"
    ]
)

comparison_table

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

100%|██████████| 50/50 [02:13<00:00,  2.68s/it]

,Recall@1,Recall@3,Recall@5,Precision@1,Precision@3,Precision@5,MRR
Dense Baseline,0.62,0.74,0.82,0.62,0.346667,0.320,0.699000
Dense + Query Expansion,0.52,0.70,0.76,0.52,0.340000,0.304,0.619667
Hybrid BM25 + Dense,0.56,0.76,0.82,0.56,0.406667,0.340,0.666333
Hybrid + Reranking,0.84,0.86,0.86,0.84,0.500000,0.408,0.850000

In [ ]:
# ============================================================
# 13. BEFORE VS AFTER RERANKING EXAMPLE
# ============================================================

sample_question = df.iloc[0]["question"]

print("QUESTION:", sample_question)

print("\nBefore reranking:")
before = hybrid_retrieve(sample_question, top_k=5)
for i, r in enumerate(before, start=1):
    print(f"[P{i}] {r['passage_id']} | {r['text'][:200]}")

print("\nAfter reranking:")
after = hybrid_rerank_retrieve(sample_question, top_k=5)
for i, r in enumerate(after, start=1):
    print(f"[P{i}] {r['passage_id']} | {r['text'][:200]}")

QUESTION: Who was the screenwriter for On the Town?

Before reranking:
[P1] On_the_Town_(film)_0 | On the Town is a 1949 American Technicolor musical film with music by Leonard Bernstein and Roger Edens and book and lyrics by Betty Comden and Adolph Green. It is an adaptation of the Broadway stage
[P2] Montgomery_Tully_1 | 1967. He also worked in television, directing episodes of shows including Edgar Wallace Mysteries, Kraft Mystery Theatre, Man from Interpol and Fabian of the Yard. == Partial filmography == == Referen
[P3] Bury,_Greater_Manchester_30 | Metropolitan Police, who was born in Bury and was responsible for the repeal of the Corn Laws in 1846. Hundreds of people climb to the tower each year on Good Friday. Historically this gathering had a
[P4] The_City_(1916_film)_0 | The City is a lost 1916 silent film based on Clyde Fitch's 1909 play, The City. It was distributed by the World Film Company. == Cast == Thurlow Bergen - George Rand, Jr. Riley Hatch - George Rand, Sr
[P5] Bury,_Greater_Manchester_0 | Bury (, ) is a market town on the River Irwell in the Metropolitan Borough of Bury, Greater Manchester, England. It had a population of 81,101 in 2021, while the wider borough had a population of 193,

After reranking:
[P1] On_the_Town_(film)_0 | On the Town is a 1949 American Technicolor musical film with music by Leonard Bernstein and Roger Edens and book and lyrics by Betty Comden and Adolph Green. It is an adaptation of the Broadway stage
[P2] Betty_Comden_3 | wrote the book and lyrics, which included sizable parts for themselves (as "Claire" and "Ozzie"). Their next musical, Billion Dollar Baby in 1945, with music by Morton Gould was not a success, and the
[P3] Musical_film_3 | regularly premiered. These works included: Meet Me in St. Louis (1944), Easter Parade (1948), On the Town (1949), An American in Paris (1951), Singin' in the Rain (1952), The Band Wagon (1953), High S
[P4] Last_Night_(2010_film)_9 | that their struggle was believable". After a negative response from a Warner Bros. studio executive on the script's formatting, she realized Final Draft was the preferred software for screenwriters. I
[P5] The_Night_They_Raided_Minsky's_10 | that the novel would be adapted by screenwriter Edward Chodorov. Later in the year, however, Key had enlisted screenwriter Julius J. Epstein. At these early stages, Sammy Cahn as well as Johnny Mercer

In [ ]:
# ============================================================
# 14. GROUNDED QA PROMPT
# ============================================================

GROUNDING_PROMPT = """
You are a factual question answering system.

Use ONLY the provided passages.
Every factual claim must include a citation like [P1], [P2], etc.
If the answer is not clearly supported by the passages, say:
"The retrieved evidence is insufficient to answer confidently."

Question:
{question}

Passages:
{passages}

Final Answer:
"""

In [ ]:
# ============================================================
# 15. OPTIONAL OPENAI SETUP
# ============================================================
USE_OPENAI = False

try:
    from openai import OpenAI
    if os.getenv("OPENAI_API_KEY"):
        client = OpenAI()
        USE_OPENAI = True
except:
    USE_OPENAI = False

print("Using OpenAI:", USE_OPENAI)

Using OpenAI: False

In [ ]:
# ============================================================
# 16. ANSWER GENERATION
# ============================================================

def format_passages(retrieved):
    formatted = []
    for i, r in enumerate(retrieved, start=1):
        formatted.append(
            f"[P{i}] Passage ID: {r['passage_id']}\nTitle: {r['title']}\nText: {r['text']}"
        )
    return "\n\n".join(formatted)

def generate_answer(question, retrieved):
    passages_text = format_passages(retrieved)

    prompt = GROUNDING_PROMPT.format(
        question=question,
        passages=passages_text
    )

    if USE_OPENAI:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You answer only using cited retrieved evidence."},
                {"role": "user", "content": prompt}
            ],
            temperature=0
        )
        return response.choices[0].message.content

    # Fallback extractive answer if no API key is used
    return f"Based on the retrieved evidence, the answer is most likely supported by [P1]. {retrieved[0]['text'][:300]}..."

In [ ]:
# ============================================================
# 17. GENERATE 10 CITED ANSWERS
# ============================================================

qa_examples = []

for i, row in df.head(10).iterrows():
    question = row["question"]
    retrieved = hybrid_rerank_retrieve(question, top_k=5)
    answer = generate_answer(question, retrieved)

    qa_examples.append({
        "question": question,
        "answer": answer,
        "retrieved_passages": retrieved
    })

for ex in qa_examples:
    print("=" * 80)
    print("QUESTION:", ex["question"])
    print("\nRETRIEVED PASSAGES:")
    for i, r in enumerate(ex["retrieved_passages"], start=1):
        print(f"[P{i}] {r['passage_id']} | {r['text'][:250]}")
    print("\nANSWER:")
    print(ex["answer"])

================================================================================
QUESTION: Who was the screenwriter for On the Town?

RETRIEVED PASSAGES:
[P1] On_the_Town_(film)_0 | On the Town is a 1949 American Technicolor musical film with music by Leonard Bernstein and Roger Edens and book and lyrics by Betty Comden and Adolph Green. It is an adaptation of the Broadway stage musical of the same name produced in 1944 (which i
[P2] Betty_Comden_3 | wrote the book and lyrics, which included sizable parts for themselves (as "Claire" and "Ozzie"). Their next musical, Billion Dollar Baby in 1945, with music by Morton Gould was not a success, and their 1947 show Bonanza Bound closed out-of-town and
[P3] Musical_film_3 | regularly premiered. These works included: Meet Me in St. Louis (1944), Easter Parade (1948), On the Town (1949), An American in Paris (1951), Singin' in the Rain (1952), The Band Wagon (1953), High Society (1956), and Gigi (1958). During this time,
[P4] Last_Night_(2010_film)_9 | that their struggle was believable". After a negative response from a Warner Bros. studio executive on the script's formatting, she realized Final Draft was the preferred software for screenwriters. In early drafts, the story was set between Los Ange
[P5] The_Night_They_Raided_Minsky's_10 | that the novel would be adapted by screenwriter Edward Chodorov. Later in the year, however, Key had enlisted screenwriter Julius J. Epstein. At these early stages, Sammy Cahn as well as Johnny Mercer and Henry Mancini were rumored to write the music

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. On the Town is a 1949 American Technicolor musical film with music by Leonard Bernstein and Roger Edens and book and lyrics by Betty Comden and Adolph Green. It is an adaptation of the Broadway stage musical of the same name produced in 1944 (which itself is an adaptation of the Jerome Robbins balle...
================================================================================
QUESTION: What is the religion of Juan Soldevilla y Romero?

RETRIEVED PASSAGES:
[P1] Juan_Soldevilla_y_Romero_0 | Juan Soldevila y Romero (29 October 1843 – 4 June 1923) was a Spanish Cardinal of the Roman Catholic Church who served as Archbishop of Zaragoza from 1901 until his death, and was elevated to the rank of cardinal in 1919. == Biography == Juan Soldevi
[P2] Juan_Soldevilla_y_Romero_1 | canon law at the seminary in Tuy. Soldevila served as a curate in three parishes in the Archdiocese of Valladolid, and became secretary to the Archbishop, Cesáreo Rodrigo y Rodríguez (1875), a cathedral canon (1883), and an archpriest (1887). Along w
[P3] Juan_Soldevilla_y_Romero_2 | for the assistance of victims of a cholera epidemic. On 14 February 1889 Soldevila was appointed Bishop of Tarazona by Pope Leo XIII; during this time he became senator for that region. He received his episcopal consecration on the following April 28
[P4] Juan_Soldevilla_y_Romero_3 | del Popolo in the consistory of 15 December 1919. He received his cardinal's biretta from King Alphonse XIII on Christmas Day of that same year. Soldevila was one of the cardinal electors who participated in the 1922 papal conclave, which selected Po
[P5] Juan_Soldevilla_y_Romero_4 | of anarchist leader Salvador Seguí. He is buried at the Basilica of Our Lady of the Pillar. == References == == External links == Cardinals of the Holy Roman Church Catholic-Hierarchy [self-published] The Anarchist Library website Durruti in the Span

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. Juan Soldevila y Romero (29 October 1843 – 4 June 1923) was a Spanish Cardinal of the Roman Catholic Church who served as Archbishop of Zaragoza from 1901 until his death, and was elevated to the rank of cardinal in 1919. == Biography == Juan Soldevila y Romero was born in Fuentelapeña, and studied ...
================================================================================
QUESTION: What genre is Haddaway?

RETRIEVED PASSAGES:
[P1] The_Album_(Haddaway_album)_0 | The Album (also known as Haddaway in North America and L'Album in France) is the debut album by Trinidadian-German Eurodance recording artist Haddaway, released in September 1993 by Coconut Records. It includes the hit singles "What Is Love", "Life",
[P2] Eurodance_8 | years, other Eurodance acts formed in Frankfurt, including Jam and Spoon, Intermission and Culture Beat. After the breakthrough single "Rhythm is a Dancer" by Snap! in 1992, new groups started to appear all over Europe, mainly in Belgium, the Netherl
[P3] The_Album_(Haddaway_album)_1 | one-hit wonder' proclaimed the posters flagging Haddaway's second single 'Life', and they were right. Nor, on the evidence here, will he stop at two hits. His career-launching 'What Is Love' is the pick of the pack for sure, but there's enough upbeat
[P4] Eurodance_9 | Alban in 1992, "No Limit" by Belgian-Dutch group 2 Unlimited in 1993, "What Is Love" by Haddaway in the same year, "Cotton Eye Joe" by Rednex in 1994, "Another Night" by Real McCoy and "Scatman (Ski-Ba-Bop-Ba-Dop-Bop)" by Scatman John in the same yea
[P5] The_Album_(Haddaway_album)_3 | on The Album, additional backing vocals on The Album 2nd Edition by Elkie Schlimbach, Rena T. Otta Alex Trime – keyboards == Charts == == Certifications and sales == == References == == External links == Overview of Album Haddaway – The Album https:/

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. The Album (also known as Haddaway in North America and L'Album in France) is the debut album by Trinidadian-German Eurodance recording artist Haddaway, released in September 1993 by Coconut Records. It includes the hit singles "What Is Love", "Life", "I Miss You" and "Rock My Heart". The lead single...
================================================================================
QUESTION: Who was the composer of Chances Are?

RETRIEVED PASSAGES:
[P1] Chances_Are_(film)_0 | Chances Are is a 1989 American romantic fantasy comedy film directed by Emile Ardolino and starring Cybill Shepherd, Robert Downey Jr., Ryan O'Neal, and Mary Stuart Masterson in Panavision. The original music score was composed by Maurice Jarre. == P
[P2] Chances_Are_(film)_10 | positive reviews from critics, but did not do well at the box office. As of May 2024, the film holds a rating of 67% on Rotten Tomatoes from 33 reviews. Roger Ebert of The Chicago Sun Times gave the film 3 and 1/2 out of 4 stars saying, “Chances Are
[P3] Stephen_Sondheim_96 | to gild the lily. It cannot be improved." The musical was later created and premiered in 2016 with music and lyrics by Tim Minchin and book by Danny Rubin (screenwriter of the film) with Sondheim's blessing. Nathan Lane said that he once approached S
[P4] Chances_Are_(film)_11 | lyrics by Dean Pitchford) performed by Cher and Peter Cetera. The song peaked at #6 on the Hot 100 in May 1989. Also featured is the song of the same title as the film sung by Johnny Mathis. Although the film contains other songs, a soundtrack album
[P5] Chances_Are_(film)_9 | Zellerbach Gianni Russo as Anthony Bonino Lester Lanin as Conductor == Production == The film was known prior to production as Life After Life and Unforgettable. Chances Are was Cybill Shepherd's first film in a number of years. Her profile had risen

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. Chances Are is a 1989 American romantic fantasy comedy film directed by Emile Ardolino and starring Cybill Shepherd, Robert Downey Jr., Ryan O'Neal, and Mary Stuart Masterson in Panavision. The original music score was composed by Maurice Jarre. == Plot == Young district attorney Louis Jeffries III ...
================================================================================
QUESTION: Who was the producer of The Pioneers?

RETRIEVED PASSAGES:
[P1] The_Pioneers_(1916_film)_0 | The Pioneers is a 1916 Australian silent film directed by Franklyn Barrett. It is considered a lost film. The film was inspired by The Pioneer, a 1904 painting by Frederick McCubbin of the Heidelberg School movement, also known as Australian impressi
[P2] Maurice_Jarre_12 | 1940s, his marriage to Francette Pejot, a French Resistance member and concentration camp survivor, produced a son, Jean-Michel Jarre, a French composer, performer, and music producer, who is one of the pioneers in electronic music. When Jean-Michel
[P3] Record_producer_2 | some artists do their own production. Some producers are their own engineers, operating the technology across the project: preproduction, recording, mixing, and mastering. Record producers' precursors were "A&R men", who likewise could blend entrepre
[P4] Record_producer_10 | A&R men writing music, record production still referred to just the manufacturing of record discs. === Record producers === After World War II, pioneering A&R managers who transitioned influentially to record production as now understood, while somet
[P5] Record_producer_30 | Pioneers: Architects of American Roots Music on Record. Vanderbilt University Press. ISBN 978-0-8265-2177-4. Massey, Howard (2000). Behind the glass. Backbeat books, San Francisco. Massey, Howard (2009). Behind the glass, Volume II. Backbeat books, S

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. The Pioneers is a 1916 Australian silent film directed by Franklyn Barrett. It is considered a lost film. The film was inspired by The Pioneer, a 1904 painting by Frederick McCubbin of the Heidelberg School movement, also known as Australian impressionism. The film was later remade by Raymond Longfo...
================================================================================
QUESTION: Who was the screenwriter for The City?

RETRIEVED PASSAGES:
[P1] Last_Night_(2010_film)_9 | that their struggle was believable". After a negative response from a Warner Bros. studio executive on the script's formatting, she realized Final Draft was the preferred software for screenwriters. In early drafts, the story was set between Los Ange
[P2] The_City_(1916_film)_0 | The City is a lost 1916 silent film based on Clyde Fitch's 1909 play, The City. It was distributed by the World Film Company. == Cast == Thurlow Bergen - George Rand, Jr. Riley Hatch - George Rand, Sr. (*as William Riley Hatch) Elsie Esmond - Emily R
[P3] The_Night_They_Raided_Minsky's_9 | claimed she was not even at the theater that night. Her father was a police officer and a straitlaced Quaker, although he never came to New York City and never led a raid on one of the Minsky burlesque houses. === Proposed Stage Show === In April 196
[P4] Joss_Whedon_4 | third-generation TV writer as a son of Tom Whedon, a screenwriter for Alice in the 1970s and The Golden Girls in the 1980s, and a grandson of John Whedon, who worked on The Donna Reed Show in the 1950s and The Dick Van Dyke Show and That Girl in the
[P5] Joss_Whedon_3 | comic book writer, both for comic book continuations of television series he created and for established franchises, such as Astonishing X-Men. Beginning in July 2020, multiple actors, producers, and writers have spoken out against Whedon about the t

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. that their struggle was believable". After a negative response from a Warner Bros. studio executive on the script's formatting, she realized Final Draft was the preferred software for screenwriters. In early drafts, the story was set between Los Angeles and New Mexico; the setting was later changed ...
================================================================================
QUESTION: In what city was Jerrold Katz born?

RETRIEVED PASSAGES:
[P1] Jerrold_Katz_0 | Jerrold Jacob Katz (14 July 1932 – 7 February 2002) was an American philosopher and linguist. == Biography == After receiving a PhD in philosophy from Princeton University in 1960, Katz became a research associate in linguistics at the Massachusetts
[P2] Jerrold_Katz_2 | Reality of Language and Its Philosophical Import (1971) Language and other Abstract Objects (1981) The Metaphysics of Meaning (1990) Realistic Rationalism (2000) Sense, Reference, and Philosophy (2004; posthum.) == Notes == == References == Obituary
[P3] Jerrold_Katz_1 | semantics in generative grammar, which he refers to as the autonomous theory of sense (ATS). Katz was a staunch defender of rationalism (although not in a Cartesian/Fregean sense) and the metaphysical import of "essences". He argued extensively again
[P4] Into_the_Woods_54 | as the Baker's Wife, Tracy Katz as Little Red, Liz McCartney as the Witch, and Patricia Ben Peterson as Cinderella at the Ordway Center for the Performing Arts in Saint Paul, Minnesota. A 2005 Stratford Festival, production in Canada, directed by Pet
[P5] Robert_Lopez_2 | == Early life == Robert Lopez was born in Manhattan, to Katherine (Lowe) and Frank Lopez. He is partly of Filipino descent through his father (who was born on a ship in the middle of the ocean after departing Manila); his paternal grandfather was Fil

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. Jerrold Jacob Katz (14 July 1932 – 7 February 2002) was an American philosopher and linguist. == Biography == After receiving a PhD in philosophy from Princeton University in 1960, Katz became a research associate in linguistics at the Massachusetts Institute of Technology in 1961. He was appointed ...
================================================================================
QUESTION: Who was the screenwriter for Sixteen Candles?

RETRIEVED PASSAGES:
[P1] Sixteen_Candles_0 | Sixteen Candles is a 1984 American coming-of-age teen comedy film starring Molly Ringwald, Michael Schoeffling, and Anthony Michael Hall. Written and directed by John Hughes in his directorial debut, it was the first in a string of films Hughes would
[P2] Sixteen_Candles_9 | to his house. Jake gives Sam her underwear, and a birthday cake with 16 candles. He tells her to make a wish and she says it already came true. They kiss. == Cast == == Production == === Development === John Hughes originally wrote Sixteen Candles in
[P3] John_Hughes_(filmmaker)_0 | John Wilden Hughes Jr. (February 18, 1950 – August 6, 2009) was an American filmmaker. He is best known for writing, directing, and producing the films Sixteen Candles (1984), The Breakfast Club (1985), Weird Science (1985), Ferris Bueller's Day Off
[P4] John_Hughes_(filmmaker)_8 | House. However, his next screenplay for them was National Lampoon's Vacation (1983), which became a major success. This, along with the popularity of his script for Mr. Mom that same year, earned him a three-film deal with Universal Pictures. Hughes'
[P5] Sixteen_Candles_21 | that is a lie." Pauline Kael wrote in The New Yorker, "It doesn't amount to much, and it's certainly not to be confused with a work of art or a work of any depth, but the young writer-director John Hughes has a knack for making you like the high-scho

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. Sixteen Candles is a 1984 American coming-of-age teen comedy film starring Molly Ringwald, Michael Schoeffling, and Anthony Michael Hall. Written and directed by John Hughes in his directorial debut, it was the first in a string of films Hughes would direct, centering on teenage life. The film follo...
================================================================================
QUESTION: Who is the author of Revolution?

RETRIEVED PASSAGES:
[P1] United_States_121 | arts in the United States, and for institutions which preserve the cultural heritage of the United States." It is composed of four sub-agencies: National Endowment for the Arts National Endowment for the Humanities Institute of Museum and Library Ser
[P2] Russell_Brand_50 | building [the House of Commons] generally speaking do not represent us, they represent their friends in big business. It's time for us to take back our power. Power isn't there, it is here, within us. The revolution that's required isn't a revolution
[P3] Revolution_(book)_3 | That same week, Brand was interviewed by Jeremy Paxman on BBC Two's current-affairs programme, Newsnight. Paxman posed to Brand the problem: "How, may I ask, is this revolution going to come about?" The book Revolution, then, is presented as an exten
[P4] Science_fiction_23 | in the 1982 short story Burning Chrome. In the same year, Octavia Butler's short story "Speech Sounds" won the Hugo Award for Best Short Story. She went on to explore themes of racial injustice, global warming, women's rights, and political conflict.
[P5] Mohsen_Makhmalbaf_9 | of hunger to a million nationwide. I concluded that nobody demolished the statue of Buddha; it crumbled out of shame. Out of shame for the world's ignorance toward Afghanistan. It broke down, knowing its greatness didn't do any good. == Early years o

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. arts in the United States, and for institutions which preserve the cultural heritage of the United States." It is composed of four sub-agencies: National Endowment for the Arts National Endowment for the Humanities Institute of Museum and Library Services Federal Council on the Arts and the Humaniti...
================================================================================
QUESTION: Who was the screenwriter for The Great Fire?

RETRIEVED PASSAGES:
[P1] The_Great_Fire_(TV_series)_0 | The Great Fire is a four-part television drama first shown on ITV from 16 October to 6 November 2014. It is set during the Great Fire of London in England in 1666. It was written by Tom Bradby and produced by Ecosse Films. Each hour-long (including c
[P2] Tom_Bradby_7 | Sundance Film Festival. Bradby wrote the ITV drama The Great Fire, broadcast in 2014. Filming began in 2025 on an ITV adaptation of his novel Secret Service, with Gemma Arterton leading the cast. == Personal life == In 1994, Bradby married Claudia, a
[P3] Tom_Bradby_6 | of Harry's memoir, Spare. On 6 May 2023, Bradby co-presented with Julie Etchingham ITV's coverage of the coronation of King Charles III and Queen Camilla. == Bibliography == === Colette McVeigh === === Julia Havilland === === Richard Field === === Sa
[P4] The_Great_Fire_(TV_series)_3 | of Richmond Uriel Emil as Signor Romero Sonya Cassidy as Catherine of Braganza == Filming locations == Cobham Hall was used to film some of the London street scenes and Penshurst Place in Kent doubled as the exterior of the King's palace. == Receptio
[P5] The_Night_They_Raided_Minsky's_10 | that the novel would be adapted by screenwriter Edward Chodorov. Later in the year, however, Key had enlisted screenwriter Julius J. Epstein. At these early stages, Sammy Cahn as well as Johnny Mercer and Henry Mancini were rumored to write the music

ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. The Great Fire is a four-part television drama first shown on ITV from 16 October to 6 November 2014. It is set during the Great Fire of London in England in 1666. It was written by Tom Bradby and produced by Ecosse Films. Each hour-long (including commercial breaks) episode is set in one day of the...

In [ ]:
# ============================================================
# 18. SELF-REFLECTION PROMPT
# ============================================================

REFLECTION_PROMPT = """
You are checking whether an answer is well grounded.

Check:
1. Does the answer use citations?
2. Is every claim supported by the retrieved passages?
3. Is the answer complete?
4. If the answer is weak, revise it using only the same passages.

Question:
{question}

Retrieved Passages:
{passages}

Original Answer:
{answer}

Return:
- Critique:
- Revised Answer:
"""

In [ ]:
# ============================================================
# 19. SELF-REFLECTION FUNCTION
# ============================================================

def reflect_answer(question, retrieved, answer):
    passages_text = format_passages(retrieved)

    prompt = REFLECTION_PROMPT.format(
        question=question,
        passages=passages_text,
        answer=answer
    )

    if USE_OPENAI:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You critique and revise answers using only cited evidence."},
                {"role": "user", "content": prompt}
            ],
            temperature=0
        )
        return response.choices[0].message.content

    # Fallback reflection
    critique = "Critique: The answer should clearly cite the retrieved passages and avoid unsupported claims."
    revised = f"Revised Answer: The answer should be based mainly on [P1]. {retrieved[0]['text'][:250]}..."
    return critique + "\n" + revised

In [ ]:
# ============================================================
# 20. BEFORE VS AFTER SELF-REFLECTION
# ============================================================

example = qa_examples[0]

reflection = reflect_answer(
    example["question"],
    example["retrieved_passages"],
    example["answer"]
)

print("QUESTION:")
print(example["question"])

print("\nORIGINAL ANSWER:")
print(example["answer"])

print("\nREFLECTION OUTPUT:")
print(reflection)

QUESTION:
Who was the screenwriter for On the Town?

ORIGINAL ANSWER:
Based on the retrieved evidence, the answer is most likely supported by [P1]. On the Town is a 1949 American Technicolor musical film with music by Leonard Bernstein and Roger Edens and book and lyrics by Betty Comden and Adolph Green. It is an adaptation of the Broadway stage musical of the same name produced in 1944 (which itself is an adaptation of the Jerome Robbins balle...

REFLECTION OUTPUT:
Critique: The answer should clearly cite the retrieved passages and avoid unsupported claims.
Revised Answer: The answer should be based mainly on [P1]. On the Town is a 1949 American Technicolor musical film with music by Leonard Bernstein and Roger Edens and book and lyrics by Betty Comden and Adolph Green. It is an adaptation of the Broadway stage musical of the same name produced in 1944 (which i...

In [ ]:
# ============================================================
# 21. FINAL COMPARATIVE EVALUATION TABLE
# ============================================================

final_system_metrics = reranked_metrics.copy()

# Retrieval metrics are usually the same as reranked retrieval.
# Self-reflection mainly improves generation quality, not retrieval ranking.
final_comparison = pd.DataFrame(
    [
        baseline_metrics,
        expanded_metrics,
        hybrid_metrics,
        reranked_metrics,
        final_system_metrics
    ],
    index=[
        "Baseline Dense Retrieval",
        "Dense Retrieval + Query Expansion",
        "Hybrid Retrieval",
        "Hybrid Retrieval + Reranking",
        "Final RAG + Self-Reflection"
    ]
)

final_comparison

,Recall@1,Recall@3,Recall@5,Precision@1,Precision@3,Precision@5,MRR
Baseline Dense Retrieval,0.62,0.74,0.82,0.62,0.346667,0.320,0.699000
Dense Retrieval + Query Expansion,0.52,0.70,0.76,0.52,0.340000,0.304,0.619667
Hybrid Retrieval,0.56,0.76,0.82,0.56,0.406667,0.340,0.666333
Hybrid Retrieval + Reranking,0.84,0.86,0.86,0.84,0.500000,0.408,0.850000
Final RAG + Self-Reflection,0.84,0.86,0.86,0.84,0.500000,0.408,0.850000

In [ ]:
# ============================================================
# 22. FAILURE ANALYSIS TEMPLATE
# ============================================================

failure_analysis = []

for i, row in df.head(5).iterrows():
    question = row["question"]
    gold = get_gold_answers(row)
    retrieved = hybrid_rerank_retrieve(question, top_k=5)
    answer = generate_answer(question, retrieved)

    retrieval_hit = any(contains_gold_answer(r["text"], gold) for r in retrieved)

    if retrieval_hit:
        failure_type = "Generation or prompting issue if answer is still incomplete."
        fix = "Improve prompt instructions or use stronger LLM."
    else:
        failure_type = "Retrieval or ranking issue."
        fix = "Improve corpus coverage, query expansion, or reranking."

    failure_analysis.append({
        "Question": question,
        "Gold Answers": gold,
        "Retrieval Hit": retrieval_hit,
        "Likely Failure Source": failure_type,
        "Possible Fix": fix
    })

failure_df = pd.DataFrame(failure_analysis)
failure_df

,Question,Gold Answers,Retrieval Hit,Likely Failure Source,Possible Fix
0,Who was the screenwriter for On the Town?,"[betty comden, basya cohen, adolph green]",True,Generation or prompting issue if answer is sti...,Improve prompt instructions or use stronger LLM.
1,What is the religion of Juan Soldevilla y Romero?,"[catholic church, roman catholic church, churc...",True,Generation or prompting issue if answer is sti...,Improve prompt instructions or use stronger LLM.
2,What genre is Haddaway?,"[eurodance, eurodance, euro dance]",True,Generation or prompting issue if answer is sti...,Improve prompt instructions or use stronger LLM.
3,Who was the composer of Chances Are?,"[maurice jarre, mauricealexis jarre]",True,Generation or prompting issue if answer is sti...,Improve prompt instructions or use stronger LLM.
4,Who was the producer of The Pioneers?,"[franklyn barrett, walter franklyn barrett]",True,Generation or prompting issue if answer is sti...,Improve prompt instructions or use stronger LLM.

In [ ]:
# ============================================================
# 23. SAVE RESULTS
# ============================================================

comparison_table.to_csv("retrieval_comparison_metrics.csv")
final_comparison.to_csv("final_system_comparison.csv")
failure_df.to_csv("failure_analysis.csv", index=False)

print("Saved:")
print("- retrieval_comparison_metrics.csv")
print("- final_system_comparison.csv")
print("- failure_analysis.csv")

Saved:
- retrieval_comparison_metrics.csv
- final_system_comparison.csv
- failure_analysis.csv